name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest
    services:
      fake-gcs-server:
        image: fsouza/fake-gcs-server:latest
        ports:
          - 4443:4443
      s3mock:
        image: fadobe/s3mock:latest
        ports:
          - 9090:9090
          - 9191:9191
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
# setup cloud emulators        
    - name: azuright
      uses: potatoqualitee/azuright@v1.1      
      

    - name:  test GCP storage
      run: |
        curl --insecure https://127.0.0.1:4443/storage/v1/b
        {"kind":"storage#buckets","items":[{"kind":"storage#bucket","id":"sample-bucket","name":"sample-bucket"}],"prefixes":null}
        curl --insecure https://0.0.0.0:4443/storage/v1/b/sample-bucket/o
        {"kind":"storage#objects","items":[{"kind":"storage#object","name":"some_file.txt","id":"sample-bucket/some_file.txt","bucket":"sample-bucket","size":"33"}],"prefixes":[]}       
      
      
      
# run build and test           
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
        DEFAULT_REGION: eu-west-1
        AWS_ACCESS_KEY_ID: localkey
        AWS_SECRET_ACCESS_KEY: localsecret


