name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest
    #services:
    #  myapp.s3:
    #    image: localstack/localstack:latest
    #    ports:
    #      - 4510:4510
    #    env:
    #      SERVICES: s3
    #      DEFAULT_REGION: eu-west-1
    #      AWS_REGION: us-west-1
    #      DEBUG: 1
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
# setup cloud emulators        
    - name: azuright
      uses: potatoqualitee/azuright@v1.1      
      
    - name: Start GCP storage
      run: |
        docker run -d --name fake-gcs-server -p 4443:4443 fsouza/fake-gcs-server
    - name:  test GCP storage
      run: |
        curl --insecure https://127.0.0.1:4443/storage/v1/b
        {"kind":"storage#buckets","items":[{"kind":"storage#bucket","id":"sample-bucket","name":"sample-bucket"}],"prefixes":null}
        curl --insecure https://0.0.0.0:4443/storage/v1/b/sample-bucket/o
        {"kind":"storage#objects","items":[{"kind":"storage#object","name":"some_file.txt","id":"sample-bucket/some_file.txt","bucket":"sample-bucket","size":"33"}],"prefixes":[]}       
      
    - name: Start S3
      run: |
        docker run -p 9090:9090 -p 9191:9191 -t adobe/s3mock

      
      
# run build and test           
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
        DEFAULT_REGION: eu-west-1
        AWS_ACCESS_KEY_ID: localkey
        AWS_SECRET_ACCESS_KEY: localsecret


