name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest
    services:
      myapp.s3:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
          - 4571:4571
        env:
          SERVICES: s3
          DEFAULT_REGION: eu-west-1
          AWS_REGION: us-west-1
          DEBUG: 1
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
# setup cloud emulators        
    - name: azuright
      uses: potatoqualitee/azuright@v1.1      
      
    - name: Start LocalStack
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
        run: |
          # install LocalStack cli and awslocal
          pip install localstack awscli-local[ver1]
          # Make sure to pull the latest version of the image
          docker pull localstack/localstack
          # Start LocalStack in the background
          localstack start -d
          # Wait 30 seconds for the LocalStack container to become ready before timing out
          echo "Waiting for LocalStack startup..."
          localstack wait -t 30
          echo "Startup complete"          
    - name: Run some Tests against LocalStack
            run: |
              awslocal s3 mb s3://test
              awslocal s3 ls
              echo "Test Execution complete!"         
      
# run build and test           
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
        DEFAULT_REGION: eu-west-1
        AWS_ACCESS_KEY_ID: localkey
        AWS_SECRET_ACCESS_KEY: localsecret


