name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest
    services:
      fake-gcs-server:
        image: fsouza/fake-gcs-server
        ports:
          - 4443:4443
      localstack:
        image: localstack/localstack:latest
        ports:
          - '4563-4599:4563-4599'
          - '8055:8080'
        env:
          SERVICES: s3
          DEBUG: 1
          DATA_DIR: /tmp/localstack/data
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
# setup cloud emulators        
    - name: azuright
      uses: potatoqualitee/azuright@v1.1      
      
      
# run build and test           
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
        DEFAULT_REGION: eu-west-1
        AWS_ACCESS_KEY_ID: localkey
        AWS_SECRET_ACCESS_KEY: localsecret


