name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
services:
  localstack:
    image: localstack/localstack
    env:
      SERVICES: s3
      DEFAULT_REGION: ap-northeast-1
      DATA_DIR: /tmp/localstack/data
    ports: [ "4566:4566" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

# setup cloud emulators        
    - name: azuright
      uses: potatoqualitee/azuright@v1.1
      
    - name: Configure localstack
      run: |
        aws configure set aws_access_key_id localstack
        aws configure set aws_secret_access_key localstack
        aws configure set default.region ap-northeast-1
        aws mb s3://my-bucket --endpoint-url=http://localhost:4566
      
# run build and test           
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
